baseURL = 'https://hazmole.github.io/beneath-a-cursed-moon-zhtw'
languageCode = 'zh-tw'
title = '詛咒月影 中文站'
theme = 'book'
publishDir = "docs"

# Book configuration
disablePathToLower = true
enableGitInfo = false

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookTheme = 'dark'
  BookToC = true
  BookSection = 'docs'
  BookSearch = false
  BookComments = false
  BookPortableLinks = true